name: Jekyll Deploy
on:
  push:
    branches: [source]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Build & Deploy to GitHub Pages
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_PAT }}
          jekyll_src: ./
          jekyll_build_options: "--verbose"
